# Generated by Django 4.1.7 on 2023-03-18 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='lastrname',
            new_name='lastname',
        ),
    ]
