# Generated by Django 4.1.7 on 2023-03-21 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_orderdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='phone',
        ),
    ]
