# Generated by Django 4.1.7 on 2023-03-28 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_orderdetails_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='email',
        ),
    ]
